spark_master_role_version     = "tenant/hgi-ci"
spark_slaves_role_version     = "tenant/hgi-ci"
spark_slaves_image_name       = "theta-hgi-image-hail-base-0.2.3"
spark_master_image_name       = "theta-hgi-image-hail-base-0.2.3"
docker_manager_image_name     = "theta-hgi-image-docker-base-0.1.2"
docker_worker_image_name      = "theta-hgi-image-docker-base-0.1.2"
