variable "region" {}
variable "env" {}
variable "jr17_public_key" {}
variable "mercury_public_key" {}
variable "external_network_name" {}
variable "subnet" {}
variable "dns_nameservers" {}
variable "host_routes" {}
variable "gateway_ip" {}
