spark_master_role_version     = "tenant/hgi-dev"
spark_slaves_role_version     = "tenant/hgi-dev"
spark_slaves_image_name       = "eta-hgi-image-hail-base-0.2.3"
spark_master_image_name       = "eta-hgi-image-hail-base-0.2.3"
docker_manager_image_name     = "eta-hgi-image-console-base-0.2.3"
docker_worker_image_name      = "eta-hgi-image-console-base-0.2.3"
